name: Auto approve

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.user.login == 'NullconCICD-Natsu'
    steps:
      - uses: hmarr/auto-approve-action@v4
