name: Workflows with for secrets

on: push

jobs:
  my-job:
    name: My Job
    runs-on: self-hosted

    steps:
    - name: Set up secret file
      env:
        FLAG: ${{ secrets.FLAG }}
      run: |
        echo $FLAG
        echo "Whoami"
        pwd
        ls -R /home/runner/actions-runner/_work/
